# Generated by Django 5.1.4 on 2025-04-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "peluqueria",
            "0004_configuracioncita_horariotrabajo_informacionnegocio_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfiguracionCita",
        ),
    ]
