# Generated by Django 5.1.6 on 2025-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0005_delete_configuracioncita'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
