# Generated by Django 5.1.6 on 2025-05-12 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0006_especialista_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
