# Generated by Django 5.1.6 on 2025-05-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0007_alter_reserva_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='clientEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
