name: Docker Build on Tag

on:
  push:
    tags:
      - '*'  # Ejecuta este workflow cuando se suba cualquier tag


jobs:
  docker-build:
    name: Docker Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Autenticarse en el registry
        if: github.ref_type == 'tag'
        uses: docker/login-action@2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Construir imagen
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/franciscomoma/gymnasio/gymnasio:${{ github.ref_name }}
            ghcr.io/franciscomoma/gymnasio/gymnasio:latest